apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:18.0.4-apache
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: nextcloud-config
        - secretRef:
            name: postgres-user-creds
        - secretRef:
            name: nextcloud
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-pv
      restartPolicy: Always
      volumes:
        - name: nextcloud-pv
          persistentVolumeClaim:
            claimName: nextcloud-pvc
