apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      #      affinity:                                            
      #        podAntiAffinity:                                   
      #          preferredDuringSchedulingIgnoredDuringExecution: 
      #          - weight: 100                                    
      #            podAffinityTerm:                               
      #              labelSelector:                               
      #                matchExpressions:                          
      #                - key: app                                 
      #                  operator: In                             
      #                  values:                                  
      #                  - bitbucket                              
      #                  - bamboo                                 
      #                  - wordpress
      #                  - wordpress-javier
      #                  key: app.kubernetes.io/instance          
      #                  operator: In                             
      #                  values:                                  
      #                  - jellyfin                               
      #              topologyKey: "kubernetes.io/hostname"        
      containers:
      - name: nextcloud
        image: nextcloud:stable-apache
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: nextcloud-config
        - secretRef:
            name: postgres-user-creds
        - secretRef:
            name: nextcloud
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-pv
      - name: redis
        image: redis:alpine
        imagePullPolicy: "Always"
        ports:
          - containerPort: 6379
      restartPolicy: Always
      nodeSelector:
        k3s.io/hostname: "node05"
      volumes:
        - name: nextcloud-pv
          persistentVolumeClaim:
            claimName: nextcloud-pvc
